version: "3.8"

services:
    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-php-fpm
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        volumes:
            - .:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80" #
            - "443:443"
        depends_on:
            - php-fpm #
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
