name: Deploy Laravel App to Production EC2

on:
  push:
    branches: ["production"]
  pull_request:
    branches: ["production"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_DOMAIN: ngabaca.${{ secrets.EC2_HOST }}.nip.io
      # Tambahkan environment variable untuk encryption key
      LARAVEL_ENV_ENCRYPTION_KEY: ${{ secrets.LARAVEL_ENV_ENCRYPTION_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- Persiapan SSH untuk EC2 ---
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # --- Bagian Deployment ke EC2 ---
      - name: Execute Deployment Script on EC2
        run: |
          echo "Starting deployment via deploy.sh on EC2..."

          # Berikan hak eksekusi pada script deploy.sh di runner GitHub Actions
          chmod +x ./deploy.sh

          # Jalankan script deployment di EC2 melalui SSH
          # Pass environment variable LARAVEL_ENV_ENCRYPTION_KEY ke script
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            export LARAVEL_ENV_ENCRYPTION_KEY='${{ secrets.LARAVEL_ENV_ENCRYPTION_KEY }}'
            bash -s
          " < ./deploy.sh

          echo "Deployment script executed on EC2."

      - name: Configure and Restart Nginx/PHP-FPM on EC2
        run: |
          # Perintah ini akan dijalankan di EC2 melalui SSH
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            # Pastikan direktori nginx_config ada di EC2
            mkdir -p ~/laravel-app-deployment/nginx_config

            # SALIN FILE NGINX CONFIG DARI REPO KE EC2
            cat ./nginx/nginx.conf | sed 's|server_name localhost;|server_name ${{ env.APP_DOMAIN }};|g' | ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'cat > ~/laravel-app-deployment/nginx_config/ngabaca.conf'

            # Hapus symbolic link default Nginx jika ada (penting untuk clean state)
            sudo rm -f /etc/nginx/sites-enabled/default || true

            # Hapus symbolic link config lama jika ada
            sudo rm -f /etc/nginx/sites-enabled/ngabaca.conf || true

            # Buat symbolic link baru untuk config Nginx yang sudah dimodifikasi
            sudo ln -s ~/laravel-app-deployment/nginx_config/ngabaca.conf /etc/nginx/sites-available/ngabaca.conf
            sudo ln -s /etc/nginx/sites-available/ngabaca.conf /etc/nginx/sites-enabled/ngabaca.conf

            # Uji konfigurasi Nginx
            sudo nginx -t

            # Restart Nginx jika pengujian sukses
            sudo systemctl restart nginx
            sudo systemctl restart php8.4-fpm # Sesuaikan versi PHP
          "
           echo "Nginx and PHP-FPM configured and restarted on EC2."

      - name: Verify Deployment (Optional)
        run: |
          echo "Verifying application access on EC2..."
          sleep 60
          curl -H "Host: ${{ env.APP_DOMAIN }}" http://${{ secrets.EC2_HOST }}
          echo ""
          echo "Application verified!"
