name: Deploy Laravel App to Production EC2

on:
  push:
    branches: ["production"]
  pull_request:
    branches: ["production"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_DOMAIN: ngabaca.${{ secrets.EC2_HOST }}.nip.io
      LARAVEL_ENV_ENCRYPTION_KEY: ${{ secrets.LARAVEL_ENV_ENCRYPTION_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- Persiapan SSH untuk EC2 ---
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # --- Bagian Deployment ke EC2 ---
      - name: Execute Deployment Script on EC2
        run: |
          echo "Starting deployment via deploy.sh on EC2.."

          chmod +x ./deploy.sh

          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            export LARAVEL_ENV_ENCRYPTION_KEY='${{ secrets.LARAVEL_ENV_ENCRYPTION_KEY }}'
            export GITHUB_REPOSITORY='${{ github.repository }}'
            bash -s
          " < ./deploy.sh

          echo "Deployment script executed on EC2."

      - name: Configure and Restart Nginx/PHP-FPM on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            mkdir -p ~/laravel-app-deployment/nginx_config
            
            cat ./nginx/nginx.conf | sed 's|server_name localhost;|server_name ${{ env.APP_DOMAIN }};|g' | ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'cat > ~/laravel-app-deployment/nginx_config/ngabaca.conf'
            
            sudo rm -f /etc/nginx/sites-enabled/default || true
            sudo rm -f /etc/nginx/sites-enabled/ngabaca.conf || true

            sudo ln -s ~/laravel-app-deployment/nginx_config/ngabaca.conf /etc/nginx/sites-available/ngabaca.conf
            sudo ln -s /etc/nginx/sites-available/ngabaca.conf /etc/nginx/sites-enabled/ngabaca.conf

            sudo nginx -t

            sudo systemctl restart nginx
            sudo systemctl restart php8.4-fpm # <-- Pastikan versi PHP ini benar di EC2
          "
          echo "Nginx and PHP-FPM configured and restarted on EC2."

      - name: Verify Deployment (Optional)
        run: |
          echo "Verifying application access on EC2..."
          sleep 60
          curl -H "Host: ${{ env.APP_DOMAIN }}" http://${{ secrets.EC2_HOST }}
          echo ""
          echo "Application verified!"
