name: Deploy Laravel App to Production EC2

on:
    push:
        branches: ['production']

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            APP_DOMAIN: ngabaca.${{ secrets.EC2_HOST }}.nip.io
            LARAVEL_ENV_ENCRYPTION_KEY: ${{ secrets.LARAVEL_ENV_ENCRYPTION_KEY }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            # --- Setup SSH untuk EC2 ---
            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.8.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Add EC2 host to known_hosts
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

            # --- Upload script dan file ke EC2 ---
            - name: Upload install-dependencies.sh
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: 'install-dependencies.sh'
                  target: '~/'

            - name: Upload deploy.sh
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: 'deploy.sh'
                  target: '~/'

            - name: Upload env.sh
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: 'env.sh'
                  target: '~/'

            - name: Upload nginx.conf
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: 'nginx/nginx.conf'
                  target: '~/laravel-app-deployment/nginx_config/'

            # --- Jalankan script install dependencies di EC2 ---
            - name: Run install-dependencies.sh on EC2
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      chmod +x ~/install-dependencies.sh
                      ~/install-dependencies.sh

            # --- Jalankan deploy.sh di EC2 ---
            - name: Run deploy.sh on EC2
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      export LARAVEL_ENV_ENCRYPTION_KEY='${{ secrets.LARAVEL_ENV_ENCRYPTION_KEY }}'
                      export GITHUB_REPOSITORY='${{ github.repository }}'
                      export DB_HOST='${{ secrets.DB_HOST }}'
                      export DB_USERNAME='${{ secrets.DB_USERNAME }}'
                      export DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
                      chmod +x ~/deploy.sh
                      ~/deploy.sh

            # --- Setup Nginx di EC2 ---
            - name: Configure and Restart Nginx/PHP-FPM on EC2
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      sed -i 's|server_name localhost;|server_name ${{ env.APP_DOMAIN }};|g' ~/laravel-app-deployment/nginx_config/nginx.conf

                      sudo rm -f /etc/nginx/sites-enabled/default || true
                      sudo rm -f /etc/nginx/sites-enabled/ngabaca.conf || true

                      sudo ln -sf ~/laravel-app-deployment/nginx_config/nginx.conf /etc/nginx/sites-available/ngabaca.conf
                      sudo ln -sf /etc/nginx/sites-available/ngabaca.conf /etc/nginx/sites-enabled/ngabaca.conf

                      echo "Testing nginx config..."
                      sudo nginx -t

                      echo "Restarting nginx and PHP-FPM..."
                      sudo systemctl restart nginx
                      sudo systemctl restart php8.4-fpm

            # --- Verifikasi deploy ---
            - name: Verify Deployment
              run: |
                  echo "Verifying application..."
                  echo "Accessing domain: https://${{ env.APP_DOMAIN }}"
                  sleep 20
                  curl -k https://${{ env.APP_DOMAIN }} || true
                  echo ""
                  echo "Application verified!"
